_core:
  default_config_hash: OQEHakzIUDx3nWOx2W5M-867WqcYLA_4mWia4mgdaqA
cdn: true
minified: true
theme: default
language_modes:
  - clike
  - css
  - htmlmixed
  - javascript
  - markdown
  - php
  - python
  - ruby
  - sql
  - twig
  - xml
  - yaml
