_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  antibot: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  blog: 0
  blog_hero: 0
  blog_paragraphs: 0
  breakpoint: 0
  ckeditor: 0
  codemirror_editor: 0
  color: 0
  colorbox: 0
  comment: 0
  config: 0
  contact: 0
  contact_emails: 0
  contact_storage: 0
  contact_tools: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  custom_ajax_form: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  devel_generate: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_image_style: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  glossary_tooltip: 0
  help: 0
  history: 0
  image: 0
  imagemagick: 0
  imce: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  maillog: 0
  mailsystem: 0
  markdown: 0
  media: 0
  media_library: 0
  media_remote: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_mobile: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  panels_ipe: 0
  path: 0
  path_alias: 0
  photoswipe: 0
  rdf: 0
  redirect: 0
  robotstxt: 0
  scheduler: 0
  search: 0
  shortcut: 0
  smtp: 0
  snippet_manager: 0
  sophron: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tooltip_taxonomy: 0
  tour: 0
  twig_debugger: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_templates: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  ww_bootstrap4_layouts: 0
  youtube: 0
  ds: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  tvi: 15
  minimal: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap: 0
  olivero: 0
  stable9: 0
  glisseo: 0
  blogger: 0
  bootstrap_cdn: 0
  bootstrap_sass: 0
  stable: 0
  classy: 0
  bootstrap4: 0
  ww_bootstrap4: 0
profile: minimal
